version: '3.9'

services:
  nextcloud:
    image: nextcloud
    restart: always
    volumes:
      - nextcloud:/var/www/html

  caddy:
    image: caddy
    restart: always
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config

volumes:
  nextcloud: {}
  caddy_data: {}
  caddy_config: {}
